<?php

//Configuration File

//contact

//name
$settings['contact']['module']['name']['value'] = "contact";
$settings['contact']['module']['name']['description'] = "module name";
//end name

//description
$settings['contact']['module']['description']['value'] = "contact is a module for email forms.";
$settings['contact']['module']['description']['description'] = "module purpose";
//end description

//version
$settings['contact']['module']['version']['value'] = "1.0";
$settings['contact']['module']['version']['description'] = "module version";
//end version

//dependancies
$settings['contact']['module']['dependencies']['value'] = "none";
$settings['contact']['module']['dependencies']['description'] = "comma delimited list of modules required by this module";
//end dependancies

return $settings['contact'];
?>





