<?php

//Configuration File

//portfolio

//name
$settings['portfolio']['module']['name']['value'] = "portfolio";
$settings['portfolio']['module']['name']['description'] = "module name";
//end name

//description
$settings['portfolio']['module']['description']['value'] = "portfolio is a simple module for handling content type used for a portfolio.";
$settings['portfolio']['module']['description']['description'] = "module purpose";
//end description

//version
$settings['portfolio']['module']['version']['value'] = "1.0";
$settings['portfolio']['module']['version']['description'] = "module version";
//end version

//dependencies
$settings['portfolio']['module']['dependencies']['value'] = "content";
$settings['portfolio']['module']['dependencies']['description'] = "comma delimited list of modules required by this module";
//end dependencies

return $settings['portfolio'];
?>





