<?php

//Configuration File

//admin

//name
$settings['admin']['module']['name']['value'] = "Admin";
$settings['admin']['module']['name']['description'] = "module name";
//end name

//description
$settings['admin']['module']['description']['value'] = "Admin is a module for the using forms to handle the settings that would be done directly in code.";
$settings['admin']['module']['description']['description'] = "module purpose";
//end description

//version
$settings['admin']['module']['version']['value'] = "1.0";
$settings['admin']['module']['version']['description'] = "module version";
//end version

//dependancies
$settings['admin']['module']['dependencies']['value'] = "none";
$settings['admin']['module']['dependencies']['description'] = "comma delimited list of modules required by this module";
//end dependancies

return $settings['admin'];
?>





