<?php

//Configuration File

//menu

//name
$settings['menu']['module']['name']['value'] = "menu";
$settings['menu']['module']['name']['description'] = "module name";
//end name

//description
$settings['menu']['module']['description']['value'] = "menu is a module for handling menu files for routes.";
$settings['menu']['module']['description']['description'] = "module purpose";
//end description

//version
$settings['menu']['module']['version']['value'] = "1.0";
$settings['menu']['module']['version']['description'] = "module version";
//end version

//dependancies
$settings['menu']['module']['dependencies']['value'] = "none";
$settings['menu']['module']['dependencies']['description'] = "comma delimited list of modules required by this module";
//end dependancies

return $settings['menu'];
?>





