<?php

//Configuration File

//content

//name
$settings['content']['module']['name']['value'] = "Content";
$settings['content']['module']['name']['description'] = "module name";
//end name

//description
$settings['content']['module']['description']['value'] = "Content is the main module for the creation of content types";
$settings['content']['module']['description']['description'] = "module purpose";
//end description

//version
$settings['content']['module']['version']['value'] = "1.0";
$settings['content']['module']['version']['description'] = "module version";
//end version

//dependencies
$settings['content']['module']['dependencies']['value'] = "none";
$settings['content']['module']['dependencies']['description'] = "comma delimited list of modules required by this module";
//end dependencies

return $settings['content'];
?>





